### ISSUE TITLE
Support of tabular resources

### ISSUE THREAD

**Issue by roll** [theodi/datapackage.rb#25]
If I've got this code right - https://github.com/theodi/datapackage.rb/blob/master/lib/datapackage/resource.rb - there is no support for tabular resources.

Unfortunately specification don't have such concept yet but in a few words if a resource have a `schema` (JSON Table Schema) attribute we could provide an extended interface to the user allowing reading tabular data.

```python
dp = DataPackage('descritptor.json')
resource = dp.resources[0]
# is resource tabular?
if resource.table:
    # resource.table == jsontableschema.Table
    # so the whole table interface is available with schema, reading etc
else:
    # resource is not tabular
```

**Comment by pezholio** [comment]
Ah, cool. That makes sense. This seems pretty easy to implement. I'll push something up

**Comment by pezholio** [comment]
I've now done this, but foolishly pushed to master - see https://github.com/theodi/datapackage.rb/commit/f6cf5801fce82f7111aab643d8e8ffafc24e7d5f

**Comment by roll** [comment]
:+1:
